/**:
  ros__parameters:

    robot_name: "ClubBot_Aver"

    wheel_diameter: 0.08        # meters
    wheel_base: 0.175           # meters

    left_max_rpm: 107
    right_max_rpm: 107

    left_ticks_per_rotation: 620
    right_ticks_per_rotation: 620

    left_forward_pin: 18
    left_backward_pin: 23
    right_forward_pin: 24
    right_backward_pin: 25

    linear_scale: 0.4
    angular_scale: 1.5

    pid_left_p: 1.2
    pid_left_i: 0.3
    pid_left_d: 0.05

    pid_right_p: 1.1
    pid_right_i: 0.3
    pid_right_d: 0.05


